spring:
  h2:
    console:
      enabled: true
      path: /h2
  application:
    name: hotel-service
  datasource:
    driverClassName: org.h2.Driver
    username: sa  
    password:
    #url: jdbc:h2:file:E:/h2data/sample
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
